name: Update WakaTime stats

on:
  schedule:
    - cron: '0 0 * * *'  # mise à jour quotidienne
  workflow_dispatch:

permissions:
  contents: write  

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update WakaTime stats in README
        uses: anmol098/waka-readme-stats@v3.0
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_MESSAGE: "Update WakaTime stats"
