name: Update WakaTime stats

on:
  schedule:
    - cron: '0 0 * * *'  # mise à jour quotidienne
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Update WakaTime stats
        uses: zhanghaoran0406/wakatime-readme-action@v2
        with:
          wakatime_api_key: ${{ secrets.WAKATIME_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          update_readme: true
          commit_message: "Update WakaTime stats"
